services:
  nginx:
    build: ./FE

  backend:
    build: ./BE

  ai:
    build: ./AI

  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data:
