services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - backend

    certbot:
      entrypoint: >
        certbot certonly --webroot
        --webroot-path=/var/www/certbot
        --email dev.seoliee49@gmail.com
        --agree-tos
        --no-eff-email
        -d k14a205.p.ssafy.io

  backend:
    env_file:
      - .env.prod
    restart: unless-stopped

  ai:
    env_file:
      - .env.prod
    restart: unless-stopped
    
  redis:
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env.prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s