server_tokens off;

server {
    listen 80;
    server_name musictogether.duckdns.org;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name musictogether.duckdns.org;

    include /etc/nginx/studion/upstream-active.conf;

    ssl_certificate     /etc/letsencrypt/live/musictogether.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/musictogether.duckdns.org/privkey.pem;

    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port  443;

    location /api/ {
        proxy_pass $backend_url;
    }

    location /oauth2/ {
        proxy_pass $backend_url;
    }

    location /login/oauth2/ {
        proxy_pass $backend_url;
    }

    location /ws/ {
        proxy_pass $backend_url;
        proxy_http_version 1.1;
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 3600s;
    }

    location / {
        proxy_pass $frontend_url;
    }
}
