spring:
  application:
    name: studion

  data:
    redis:
      host: localhost
      port: 6379

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET}

websocket:
  endpoint: /ws/projects
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5173